### ISSUE TITLE
Error when upgrading from 11.0.3 -> 12.0 Beta 4

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/updater#114]
I recently upgraded frmo 11.0.1 to 11.0.3 using updater.phar. WHen I changed the channel to beta, got the notification about v12 Beta 4 and used updater.phar again, it breaks. Here's the cli output:

```
Nextcloud Updater - version: v12.0.0beta2

Current version is 12.0 beta 4.

Update to Nextcloud 12.0.0 Beta 4 available. (channel: "beta")
Following file will be downloaded automatically: https://download.nextcloud.com/server/prereleases/nextcloud-12.0.0beta4.zip                                                                

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[ ] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✘] Done failed
RecursiveDirectoryIterator::__construct(/home/yunohost.app/nextcloud/data/updater-oc3seonmlmh9/downloads/nextcloud/): failed to open dir: No such file or directory

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✘] Check for expected files failed
The following extra files have been found:
    autotest-checkers.sh

Update failed. To resume or retry just execute the updater again.

```

I'm using Yunohost 2.5 which is based on Debian Jessie, Nginx, MariaDB.

Nextcloud.log errors:

```
{"reqId":"xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"192.168.1.12","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/Nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/Nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/Nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"user\"}","level":4,"time":"2017-05-19T06:09:57+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user","version":"11.0.3.2"}
{"reqId":"xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"192.168.1.12","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/Nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/Nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/Nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"user\"}","level":4,"time":"2017-05-19T06:10:01+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user","version":"11.0.3.2"}
```

So is there any other info that you need?

**Comment by MorrisJobke** [comment]
> RecursiveDirectoryIterator::__construct(/home/yunohost.app/nextcloud/data/updater-oc3seonmlmh9/downloads/nextcloud/): failed to open dir: No such file or directory

I have seen this as well, but can't explain it for now. At least the update runs fine after this message.



> [✘] Check for expected files failed
> The following extra files have been found:
>     autotest-checkers.sh

That one is actually a problem and we have fixed it. (see https://help.nextcloud.com/t/earn-a-t-shirt-by-testing-nextcloud-12-beta-2/12374/56?u=morrisjobke) As workaround delete this file and run the update again.

Sorry for the inconvenience :(

And thanks for testing.

**Comment by Bugsbane** [comment]
No problem. I keep it all running in a VM with snapshots, so reverting is about 3 clicks. Just happy to help where I can.

**Comment by Bugsbane** [comment]
Hmm... removed autotest-checkers.sh and ran updater.phar again, and now I get this after saying yes to running the occ upgrade command:

> PHP Fatal error:  Class '\OC\Memcache\APC' not found in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 116

As I said before, I can easily revert and run the whole thing again after removing the autotest file again, but if it's of any use to you, I'm happy to provide any info about the machine's current state.

**Comment by MorrisJobke** [comment]
@Bugsbane Could you disable the opcache in your PHP ini and run the upgrade again? Because this looks suspicious. :/

**Comment by Bugsbane** [comment]
I disabled opcache (I needed to in both php.ini and in NC's config.php) and yes, it worked fine after that. I wonder how we could alter the updater to work around that? Anyway, thanks for your help @MorrisJobke !

**Comment by MorrisJobke** [comment]
> I disabled opcache (I needed to in both php.ini and in NC's config.php) and yes, it worked fine after that. I wonder how we could alter the updater to work around that? Anyway, thanks for your help @MorrisJobke !

Happened already: https://github.com/nextcloud/updater/pull/115/files 😉
