### ISSUE TITLE
Nextcloud update break after update (not sure where)

### ISSUE THREAD

**Issue by codeHatcher** [nextcloud/updater#166]
I did an update, my chrome browser happened to crash and now upon revisiting I see the following which has been stuck here for about 60 minutes.

![image](https://user-images.githubusercontent.com/5360982/40860523-aee95550-65b3-11e8-9eba-c2ea4fa3fc4d.png)

where are the instructions on posting a github issue btw? I can pull whatever logs you need just don't know where anything is. I'm on version 12 I believe and did the update via the webui

**Comment by codeHatcher** [comment]
unfortunate timing as I'm dead in the water here

**Comment by codeHatcher** [comment]
updater.log
```
S3QFUmoMjKoOvo1Q4s7UQv0xE5TUDC4XFIW6q1ly1Z/XRPZaywstv3br8J52L6+J
G2ZuS4ms5s9o5i2OrogYRQ==
)

2018-06-01T12:32:12-0700 siGfXIa6uM [info] storage location: /data/updater-ocnpv5xfyws3/downloads/
2018-06-01T12:32:12-0700 siGfXIa6uM [info] end of verifyIntegrity()
2018-06-01T12:32:12-0700 siGfXIa6uM [info] endStep("6")
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] request to updater
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] currentStep()
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] Step 6 is in state "end".
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] POST request for step "7"
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] startStep("7")
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] extractDownload()
2018-06-01T12:32:12-0700 LAXxAKqoJE [info] storage location: /data/updater-ocnpv5xfyws3/downloads/
2018-06-01T12:32:18-0700 LAXxAKqoJE [info] end of extractDownload()
2018-06-01T12:32:18-0700 LAXxAKqoJE [info] endStep("7")
2018-06-01T12:32:18-0700 riIVlULh5W [info] request to updater
2018-06-01T12:32:18-0700 riIVlULh5W [info] currentStep()
2018-06-01T12:32:18-0700 riIVlULh5W [info] Step 7 is in state "end".
2018-06-01T12:32:18-0700 riIVlULh5W [info] POST request for step "8"
2018-06-01T12:32:18-0700 riIVlULh5W [info] startStep("8")
2018-06-01T12:32:18-0700 riIVlULh5W [info] replaceEntryPoints()
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace index.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace status.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace remote.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace public.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace ocs/v1.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] replace ocs/v2.php
2018-06-01T12:32:18-0700 riIVlULh5W [info] end of replaceEntryPoints()
2018-06-01T12:32:18-0700 riIVlULh5W [info] endStep("8")
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] request to updater
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] currentStep()
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] Step 8 is in state "end".
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] POST request for step "9"
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] startStep("9")
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] deleteOldFiles()
2018-06-01T12:32:18-0700 Ak6XPYd4VK [error] POST request failed with other exception
2018-06-01T12:32:18-0700 Ak6XPYd4VK [error] Exception: Exception
Message: Could not rmdir /config/www/nextcloud/updater/../apps/activity
Code:0
Trace:
#0 /config/www/nextcloud/updater/index.php(869): Updater->recursiveDelete('/config/www/nex...')
#1 /config/www/nextcloud/updater/index.php(1309): Updater->deleteOldFiles()
#2 {main}
File:/config/www/nextcloud/updater/index.php
Line:850

2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] rollbackChanges("9")
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] unlink .step
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] rollbackChanges - step >= 7
2018-06-01T12:32:18-0700 Ak6XPYd4VK [info] end of  rollbackChanges()
```

**Comment by codeHatcher** [comment]
when I turn off maintenance mode and rerun upgrade I get "nextcloud is already latest version" but still shows updating in browser

![pasted_image_6_1_18__4_18_pm](https://user-images.githubusercontent.com/5360982/40861579-85936d2c-65b7-11e8-936f-83bbe8ba8820.png)

**Comment by codeHatcher** [comment]
hey guys, I didn't have enough time to mess around with this so I just downloaded the new version, copied my config and restarted

**Comment by kesselb** [comment]
You had more luck with the newer updates?
