### ISSUE TITLE
Update fails when there is not enough disk space (I assume that is the reason)

### ISSUE THREAD

**Issue by 717g301github** [nextcloud/updater#175]
As given and explained here:
https://help.nextcloud.com/t/failure-to-upgrade-to-13-0-4/33284/4

# [Failure to upgrade to 13.0.4](https://help.nextcloud.com/t/failure-to-upgrade-to-13-0-4/33284)

[support](https://help.nextcloud.com/c/support)

[nc13](https://help.nextcloud.com/tags/nc13)

[update\_problems](https://help.nextcloud.com/tags/update_problems)

-----

[**rcdrun**](https://help.nextcloud.com/u/rcdrun) 2018-06-23 13:31:38
UTC  \#1

Nextcloud version: 13.0.4  
Operating system and version: Debian Jessy  
Apache or nginx version nginx 1.10.3  
PHP version: PHP 7.0.27-0+deb9u1

The issue you are facing:

after upgrade nextcloud does not work, following error is here:

PHP Warning:
require(/var/www/websites/website/3rdparty/composer/…/guzzlehttp/promises/src/functions\_include.php):
failed to open stream: No such file or directory in
/var/www/websites/website/3rdparty/composer/autoload\_real.php on line
61  
PHP Fatal error: require(): Failed opening required
‘/var/www/websites/website/3rdparty/composer/…/guzzlehttp/promises/src/functions\_include.php’
(include\_path=’/var/www/websites/website/3rdparty/pear/console\_getopt:/var/www/websites/website/3rdparty/pear/pear\_exception:/var/www/websites/website/3rdparty/pear/pear-core-minimal/src:/var/www/websites/website/3rdparty/pear/archive\_tar:/var/www/websites/website/apps’)
in /var/www/websites/website/3rdparty/composer/autoload\_real.php on
line 61

Is this the first time you’ve seen this error? Yes

Steps to replicate it:

1.  upgrade from previous to 13.0.4. version

The output of your Nextcloud log in **Admin \> Logging**:

    Cannot login there

Please how can I either downgrade?

Or to disable some applications if applications are causing it?

-----

[**tflidd**](https://help.nextcloud.com/u/tflidd) 2018-06-24 11:16:47
UTC  \#2

How did you upgrade? At which step of the update did this happen?

Previous version, do you mean NC 12? Or 13.0.2?

-----

[**rcdrun**](https://help.nextcloud.com/u/rcdrun) 2018-06-24 11:29:57
UTC  \#3

I have solved my problem by manually downloading and going through
upgrade process.

Then I found out that only 258 megabytes were left on hard disk.

My guess is that the upgrade could not be finished due to low disk
space. Maybe, I don’t know, but maybe the upgrade process is copying all
files, or making a copy and if there is not enough free space, there can
be a problem.

However, even such situation shall be prevented by making a check in the
upgrade process, so that it does not happen. If that was the case.

-----

[**tflidd**](https://help.nextcloud.com/u/tflidd) 2018-06-24 13:28:53
UTC  \#4

> However, even such situation shall be prevented by making a check in
> the upgrade process, so that it does not happen. If that was the case.

Indeed, can you open a feature request on the updater-app-repo:
<https://github.com/nextcloud/updater/issues>

**Comment by eppfel** [comment]
Not only fails the update, it removed my config and I had to recover it from a server backup.
In my case, running out of disk space means loosing write access.

```
2018-06-29T22:00:19+0200 DGPisCpDxJ [info] request to updater
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] currentStep()
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] show HTML page
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] current version: 13.0.2 build time: 2018-04-26T07:24:07+00:00 2495577a3be388d39b2850a70cd039866c9b09b4
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] getUpdateServerResponse()
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] updaterServer: https://updates.nextcloud.org/updater_server/
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] releaseChannel: stable
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] internal version: 13.0.2.1
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] updateURL: https://updates.nextcloud.org/updater_server/?version=13x0x2x1xxxstablexx2018-04-26T07%3A24%3A07%2B00%3A00+2495577a3be388d39b2850a70cd039866c9b09b4x7x0x29
2018-06-29T22:00:20+0200 DGPisCpDxJ [info] getUpdateServerResponse response: Array
(
    [version] => 13.0.4.0
    [versionstring] => Nextcloud 13.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-13.0.4.zip
    [web] => https://docs.nextcloud.com/server/13/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [eol] => 0
    [signature] => OogV1NE98yxer6atJPOgXBxnVgAuME94UoZ1TlgTGUw0KYqvKNwKKQ+gqzJ3ZL9t
XJuHAYQi2Uk0iblIA3TFuDALU/wA3th2PMoobHtzR4FFzDUvb88FdgKxBAOhh9n0
1PwiLBYT1FuDJn+fQLmbXWbPVlfFOOsyPFxysl1nXztxSJ7FsPgIE/MGvqKnk4L3
5iG3o/UAbqmmKNQpn7gJw4BYdf3mkJcBOgdRrcy3MXqLh9dIAXkK5HcKOD3A+Uvy
amApr7+j7zp0QlnhrObLBWramdSqmS2Udt/TdN1XhMF/9Nzq+qod6aJ8qCz9aqEb
PUPFcPmm6YQgra/1OoMTpg==
)

2018-06-29T22:00:20+0200 DGPisCpDxJ [info] checkForUpdate() Array
(
    [version] => 13.0.4.0
    [versionstring] => Nextcloud 13.0.4
    [url] => https://download.nextcloud.com/server/releases/nextcloud-13.0.4.zip
    [web] => https://docs.nextcloud.com/server/13/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [eol] => 0
    [signature] => OogV1NE98yxer6atJPOgXBxnVgAuME94UoZ1TlgTGUw0KYqvKNwKKQ+gqzJ3ZL9t
XJuHAYQi2Uk0iblIA3TFuDALU/wA3th2PMoobHtzR4FFzDUvb88FdgKxBAOhh9n0
1PwiLBYT1FuDJn+fQLmbXWbPVlfFOOsyPFxysl1nXztxSJ7FsPgIE/MGvqKnk4L3
5iG3o/UAbqmmKNQpn7gJw4BYdf3mkJcBOgdRrcy3MXqLh9dIAXkK5HcKOD3A+Uvy
amApr7+j7zp0QlnhrObLBWramdSqmS2Udt/TdN1XhMF/9Nzq+qod6aJ8qCz9aqEb
PUPFcPmm6YQgra/1OoMTpg==
)

2018-06-29T22:00:20+0200 DGPisCpDxJ [info] end of checkForUpdate() Update to Nextcloud 13.0.4 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-13.0.4.zip</code>
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] request to updater
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] currentStep()
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] POST request for step "1"
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] startStep("1")
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] checkForExpectedFilesAndFolders()
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] end of checkForExpectedFilesAndFolders()
2018-06-29T22:00:27+0200 4alYtGpN6Q [info] endStep("1")
2018-06-29T22:00:30+0200 euENLpUGV7 [info] request to updater
2018-06-29T22:00:30+0200 euENLpUGV7 [info] currentStep()
2018-06-29T22:00:30+0200 euENLpUGV7 [info] Step 1 is in state "end".
2018-06-29T22:00:30+0200 euENLpUGV7 [info] POST request for step "2"
2018-06-29T22:00:30+0200 euENLpUGV7 [info] startStep("2")
2018-06-29T22:00:30+0200 euENLpUGV7 [info] checkWritePermissions()
2018-06-29T22:00:30+0200 euENLpUGV7 [info] end of checkWritePermissions()
2018-06-29T22:00:30+0200 euENLpUGV7 [info] endStep("2")
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] request to updater
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] currentStep()
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] Step 2 is in state "end".
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] POST request for step "3"
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] startStep("3")
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] setMaintenanceMode("true")
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] configFileName /var/www/virtual/eppcloud/html/updater/../config/config.php
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] end of setMaintenanceMode()
2018-06-29T22:00:31+0200 o5hBMLYEvs [info] endStep("3")
2018-06-29T22:00:31+0200 P88FrAhQdP [info] request to updater
2018-06-29T22:00:31+0200 P88FrAhQdP [info] currentStep()
2018-06-29T22:00:31+0200 P88FrAhQdP [info] Step 3 is in state "end".
2018-06-29T22:00:31+0200 P88FrAhQdP [info] POST request for step "4"
2018-06-29T22:00:31+0200 P88FrAhQdP [info] startStep("4")
2018-06-29T22:00:31+0200 P88FrAhQdP [info] createBackup()
2018-06-29T22:00:58+0200 P88FrAhQdP [error] POST request failed with other exception
2018-06-29T22:00:58+0200 P88FrAhQdP [error] Exception: Exception
Message: Could not copy "/var/www/virtual/eppcloud/html/core/doc/user/_images/contacts_empty.png" to "/home/eppcloud/ocdata/updater-ocztm7fxpnfx/backups/nextcloud-13.0.2.1/core/doc/user/_images/contacts_empty.png"
Code:0
Trace:
#0 /var/www/virtual/eppcloud/html/updater/index.php(1294): Updater->createBackup()
#1 {main}
File:/var/www/virtual/eppcloud/html/updater/index.php
Line:503

2018-06-29T22:00:58+0200 P88FrAhQdP [info] rollbackChanges("4")
2018-06-29T22:00:58+0200 P88FrAhQdP [info] unlink .step
2018-06-29T22:00:58+0200 P88FrAhQdP [info] end of  rollbackChanges()
2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] request to updater
2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] currentStep()
2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] POST request for step "4"
2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] startStep("4")
2018-06-29T22:01:55+0200 Ai0VgtCGhI [error] POST request failed with other exception
2018-06-29T22:01:55+0200 Ai0VgtCGhI [error] Exception: Exception
Message: Could not write to .step
Code:0
Trace:
#0 /var/www/virtual/eppcloud/html/updater/index.php(1083): Updater->writeStep('start', 4)
#1 /var/www/virtual/eppcloud/html/updater/index.php(1282): Updater->startStep(4)
#2 {main}
File:/var/www/virtual/eppcloud/html/updater/index.php
Line:1073

2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] rollbackChanges("4")
2018-06-29T22:01:55+0200 Ai0VgtCGhI [info] unlink .s%
```

**Comment by 717g301github** [comment]
I did not keep data directory separately, so I was left with some about 250+ megabytes, and I just have clue that it was maybe because of low space, but I cannot be sure, as I could not repeat the process. So that is a clue, not definite cause on why it failed.

**Comment by eppfel** [comment]
@MorrisJobke Can't really tell. It is shared server, so it was not actually any partition running full, but some kind of limit in usage.
