### ISSUE TITLE
[Bug] Updater CLI - PHP Error: Call to undefined function NC\Updater\system()

### ISSUE THREAD

**Issue by MrDariusz** [nextcloud/updater#581]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

During the update to a newer version using the command:

`php --define apc.enable_cli=1 "/home/cloud.domain/updater/updater.phar --no-interaction --no-backup
`

I encountered the following errors:
```
Nextcloud Updater - version: v29.0.0-1-g9293bcb dirty

Current version is 29.0.5.

Update to Nextcloud 29.0.6 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
Open changelog ↗

Updater run in non-interactive mode.

Start update

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.
Updater run in non-interactive mode - will start "occ upgrade" now.

PHP Fatal error:  Uncaught Error: Call to undefined function NC\Updater\system() in phar:///home/cloud.domain/public_html/updater/updater.phar/lib/UpdateCommand.php:310
Stack trace:
#0 phar:///home/cloud.domain/public_html/updater/updater.phar/vendor/symfony/console/Command/Command.php(298): NC\Updater\UpdateCommand->execute()
nextcloud/server#1 phar:///home/cloud.domain/public_html/updater/updater.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
nextcloud/server#2 phar:///home/cloud.domain/public_html/updater/updater.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
nextcloud/server#3 phar:///home/cloud.domain/public_html/updater/updater.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
nextcloud/server#4 phar:///home/cloud.domain/public_html/updater/updater.phar/updater.php(10): Symfony\Component\Console\Application->run()
nextcloud/server#5 /home/cloud.domain/public_html/updater/updater.phar(14): require('...')
nextcloud/server#6 {main}
  thrown in phar:///home/cloud.domain/public_html/updater/updater.phar/lib/UpdateCommand.php on line 310
```
I had to manually run the occ:upgrade command in the root directory, because something didn't work automatically this time.

### Steps to reproduce

Run php --define apc.enable_cli=1 "/home/cloud.domain/updater/updater.phar --no-interaction --no-backup

### Expected behavior

I wanted to update without PHP Fatal errors.

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.6.1",
        "default_phone_region": "PL",
        "default_language": "pl",
        "default_locate": "pl_PL",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "maintenance_window_start": 1,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
php occ app:list
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - text: 3.10.1
  - theming: 2.4.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.18.0
  - user_ldap: 1.20.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - bruteforcesettings: 2.9.0
  - comments: 1.19.0 (installed 1.19.0)
  - contactsinteraction: 1.10.0 (installed 1.10.0)
  - dashboard: 7.9.0 (installed 7.9.0)
  - encryption: 2.17.0 (installed 2.17.0)
  - files_external: 1.21.0 (installed 1.21.0)
  - files_reminders: 1.2.0 (installed 1.2.0)
  - nextcloud_announcements: 1.18.0 (installed 1.18.0)
  - recommendations: 2.1.0 (installed 2.1.0)
  - richdocuments: 8.4.4 (installed 8.4.4)
  - sharebymail: 1.19.0 (installed 1.19.0)
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0 (installed 1.19.0)
  - testing: 1.19.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1 (installed 1.19.1)
  - user_status: 1.9.0 (installed 1.9.0)
  - weather_status: 1.9.0 (installed 1.9.0)
```

### Nextcloud Logs

```shell
updater.log
2024-08-21T10:00:11+0000 HJPOYlC0wY [info] end of checkForUpdate() No update available.
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] updater cli is executed
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] currentStep()
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] current version: 29.0.5 build time: 
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] getUpdateServerResponse()
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] updaterServer: https://updates.nextcloud.com/updater_server/
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] releaseChannel: stable
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] internal version: 29.0.5.1
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] updateURL: https://updates.nextcloud.com/updater_server/?version=29x0x5x1xxxstablexxx8x2x22
2024-08-21T10:07:57+0000 Joon6Xq3GK [info] checkForUpdate() Array
(
)

2024-08-21T10:07:57+0000 Joon6Xq3GK [info] end of checkForUpdate() No update available.
2024-09-05T15:15:09+0000 GYxos26SqH [info] updater cli is executed
2024-09-05T15:15:09+0000 GYxos26SqH [info] currentStep()
2024-09-05T15:15:09+0000 GYxos26SqH [info] current version: 29.0.5 build time: 
2024-09-05T15:15:09+0000 GYxos26SqH [info] getUpdateServerResponse()
2024-09-05T15:15:09+0000 GYxos26SqH [info] updaterServer: https://updates.nextcloud.com/updater_server/
2024-09-05T15:15:09+0000 GYxos26SqH [info] releaseChannel: stable
2024-09-05T15:15:09+0000 GYxos26SqH [info] internal version: 29.0.5.1
2024-09-05T15:15:09+0000 GYxos26SqH [info] updateURL: https://updates.nextcloud.com/updater_server/?version=29x0x5x1xxxstablexxx8x1x29
2024-09-05T15:15:14+0000 GYxos26SqH [info] getUpdateServerResponse response: Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:15:14+0000 GYxos26SqH [info] checkForUpdate() Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:15:14+0000 GYxos26SqH [info] getChangelogURL()
2024-09-05T15:15:14+0000 GYxos26SqH [info] end of checkForUpdate() Update to Nextcloud 29.0.6 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip</code><br /><a class="external_link" href="https://nextcloud.com/changelog/#29-0-6" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2024-09-05T15:15:14+0000 GYxos26SqH [info] updater run in non-interactive mode
2024-09-05T15:15:14+0000 GYxos26SqH [info] updater started
2024-09-05T15:15:14+0000 GYxos26SqH [info] executeStep request for step "1"
2024-09-05T15:15:14+0000 GYxos26SqH [info] startStep("1")
2024-09-05T15:15:14+0000 GYxos26SqH [info] checkForExpectedFilesAndFolders()
2024-09-05T15:15:14+0000 GYxos26SqH [error] executeStep request failed with UpdateException
2024-09-05T15:15:14+0000 GYxos26SqH [error] Exception: NC\Updater\UpdateException
Message: 
Code:0
Trace:
#0 phar:///home/cloud.domain.com/public_html/updater/updater.phar/lib/UpdateCommand.php(367): NC\Updater\Updater->checkForExpectedFilesAndFolders()
nextcloud/server#1 phar:///home/cloud.domain.com/public_html/updater/updater.phar/lib/UpdateCommand.php(237): NC\Updater\UpdateCommand->executeStep()
nextcloud/server#2 phar:///home/cloud.domain.com/public_html/updater/updater.phar/vendor/symfony/console/Command/Command.php(298): NC\Updater\UpdateCommand->execute()
nextcloud/server#3 phar:///home/cloud.domain.com/public_html/updater/updater.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
nextcloud/server#4 phar:///home/cloud.domain.com/public_html/updater/updater.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
nextcloud/server#5 phar:///home/cloud.domain.com/public_html/updater/updater.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
nextcloud/server#6 phar:///home/cloud.domain.com/public_html/updater/updater.phar/updater.php(10): Symfony\Component\Console\Application->run()
nextcloud/server#7 /home/cloud.domain.com/public_html/updater/updater.phar(14): require('...')
nextcloud/server#8 {main}
File:phar:///home/cloud.domain.com/public_html/updater/updater.phar/lib/Updater.php
Line:315
Data:
Array
(
    [0] => SECURITY.md
    [1] => autotest-checkers.sh
    [2] => webpack.config.js
    [3] => custom.d.ts
    [4] => tsconfig.json
    [5] => CODE_OF_CONDUCT.md
    [6] => psalm-ocp.xml
    [7] => psalm.xml
    [8] => Makefile
    [9] => __tests__
    [10] => tests
    [11] => DESIGN.md
    [12] => README.md
    [13] => autotest-external.sh
    [14] => COPYING-README
    [15] => autotest.sh
    [16] => cypress.config.ts
    [17] => webpack.modules.js
    [18] => __mocks__
    [19] => webpack.common.js
    [20] => contribute
    [21] => codecov.yml
    [22] => jest.config.ts
    [23] => cypress.d.ts
    [24] => vendor-bin
    [25] => build
    [26] => cypress
    [27] => babel.config.js
)


2024-09-05T15:15:14+0000 GYxos26SqH [info] rollbackChanges("1")
2024-09-05T15:15:14+0000 GYxos26SqH [info] unlink .step
2024-09-05T15:15:14+0000 GYxos26SqH [info] end of  rollbackChanges()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updater cli is executed
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] currentStep()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] current version: 29.0.5 build time: 
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] getUpdateServerResponse()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updaterServer: https://updates.nextcloud.com/updater_server/
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] releaseChannel: stable
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] internal version: 29.0.5.1
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updateURL: https://updates.nextcloud.com/updater_server/?version=29x0x5x1xxxstablexxx8x1x29
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] getUpdateServerResponse response: Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] checkForUpdate() Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] getChangelogURL()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] end of checkForUpdate() Update to Nextcloud 29.0.6 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip</code><br /><a class="external_link" href="https://nextcloud.com/changelog/#29-0-6" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updater run in non-interactive mode
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updater started
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] executeStep request for step "1"
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] startStep("1")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] checkForExpectedFilesAndFolders()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] end of checkForExpectedFilesAndFolders()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] endStep("1")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] executeStep request for step "2"
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] startStep("2")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] checkWritePermissions()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] end of checkWritePermissions()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] endStep("2")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] executeStep request for step "3"
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] startStep("3")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] endStep("3")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] executeStep request for step "4"
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] startStep("4")
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] downloadUpdate()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] getUpdateServerResponse()
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updaterServer: https://updates.nextcloud.com/updater_server/
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] releaseChannel: stable
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] internal version: 29.0.5.1
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] updateURL: https://updates.nextcloud.com/updater_server/?version=29x0x5x1xxxstablexxx8x1x29
2024-09-05T15:18:34+0000 QQVHRLsNs4 [info] getUpdateServerResponse response: Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] end of downloadUpdate()
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] endStep("4")
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] executeStep request for step "5"
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] startStep("5")
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] verifyIntegrity()
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] getUpdateServerResponse()
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] updaterServer: https://updates.nextcloud.com/updater_server/
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] releaseChannel: stable
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] internal version: 29.0.5.1
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] updateURL: https://updates.nextcloud.com/updater_server/?version=29x0x5x1xxxstablexxx8x1x29
2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] getUpdateServerResponse response: Array
(
    [version] => 29.0.6.1
    [versionstring] => Nextcloud 29.0.6
    [url] => https://download.nextcloud.com/server/releases/nextcloud-29.0.6.zip
    [web] => https://docs.nextcloud.com/server/29/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=29.0.6
    [autoupdater] => 1
    [eol] => 0
    [signature] => dpGb7KrKfgVFQGkLT53R6eeJZzmP24W45MknMQtZxJspSrr9eFwO2b6DrNnFbp+O
ZlxxEJ7Gx43IZN0KGCiAJQLig3BMPBnJH/kIM4gmju37sH4H6P4Dkbip+LFmmXuZ
UXddf/vUlvD5uP7XWKyiZM1rDw+Zahk3P6iVAiaYsAHkgE+eqhjBRwGdJX5YoKm9
613zgb5qy/HUljWt2LhenTnlNY/2hKiVOm8WxlxbDA7h6vKt1DVJEtqUgsuAda12
dpGvrlPFMYGAout8Rj9g4McnNioxV9G8Xj7NIT8eM2t3I/h2yLL9qVnsIcaMO4Z9
dVPC49uU0x69dX1jP042xg==
)

2024-09-05T15:18:50+0000 QQVHRLsNs4 [info] storage location: /home/cloud.domain.com/public_html/data/updater-occp6v1qq1nu/downloads/
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] end of verifyIntegrity()
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] endStep("5")
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] executeStep request for step "6"
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] startStep("6")
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] extractDownload()
2024-09-05T15:18:51+0000 QQVHRLsNs4 [info] storage location: /home/cloud.domain.com/public_html/data/updater-occp6v1qq1nu/downloads/
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] end of extractDownload()
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] endStep("6")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] executeStep request for step "7"
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] startStep("7")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] setMaintenanceMode("true")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] configFileName /home/cloud.domain.com/public_html/updater/../config/config.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] end of setMaintenanceMode()
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] endStep("7")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] executeStep request for step "8"
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] startStep("8")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replaceEntryPoints()
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace index.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace status.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace remote.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace public.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace ocs/v1.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] replace ocs/v2.php
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] end of replaceEntryPoints()
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] endStep("8")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] executeStep request for step "9"
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] startStep("9")
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] deleteOldFiles()
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] config sample exists
2024-09-05T15:18:58+0000 QQVHRLsNs4 [info] themes README exists
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] end of deleteOldFiles()
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] endStep("9")
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] executeStep request for step "10"
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] startStep("10")
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] moveNewVersionInPlace()
2024-09-05T15:18:59+0000 QQVHRLsNs4 [info] storage location: /home/cloud.domain.com/public_html/data/updater-occp6v1qq1nu/downloads/nextcloud/
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] end of moveNewVersionInPlace()
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] endStep("10")
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] executeStep request for step "12"
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] startStep("12")
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] finalize()
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] storage location: /home/cloud.domain.com/public_html/data/updater-occp6v1qq1nu/downloads/nextcloud/
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] call opcache_reset()
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] end of finalize()
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] endStep("12")
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] update of code successful.
2024-09-05T15:19:01+0000 QQVHRLsNs4 [info] updater run in non-interactive mode - occ upgrade is started
```

### Additional info

```
OS="Ubuntu 22.04.4 LTS (Jammy Jellyfish)"
```

**Comment by joshtrichards** [comment]
> `PHP Fatal error:  Uncaught Error: Call to undefined function NC\Updater\system() in phar:///home/cloud.domain/public_html/updater/updater.phar/lib/UpdateCommand.php:310`

This indicates something is restricted in your server environment. My guess is you're in some highly restricted shared hosting environment where `system()` has been disabled for PHP.
