### ISSUE TITLE
Updater ignores proxy configured in config.php

### ISSUE THREAD

**Issue by jkroepke** [nextcloud/updater#74]
Currently, the updater ignored the proxy configured in the config.php If I open the app, I got this error:

```
2017/01/06 17:40:13 [error] 301#301: *179394 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to updates.nextcloud.org port 443: No route to host in /var/www/owncloud.atu-clan.de/htdocs/updater/index.php:514
Stack trace:
#0 /htdocs/updater/index.php(224): Updater->getUpdateServerResponse()
#1 /htdocs/updater/index.php(1443): Updater->checkForUpdate()
#2 {main}
  thrown in /htdocs/updater/index.php on line 514
```

**Comment by MorrisJobke** [comment]
Thanks @jkroepke for the feedback
