### ISSUE TITLE
Updater doesn't even start. Needs to show an error message to the user

### ISSUE THREAD

**Issue by oparoz** [nextcloud/updater#84]
When doing it via the admin page. There is one line being shown about doing the update and then nothing happens.
There needs to be an error message if the process is not going to even start.

From the command line, I get this:

```
Nextcloud Updater - version: 1.0.3

Current version is 11.0.0.


  [Exception]
  Could not do request to updater server: error setting certificate verify locations:
    CAfile: /usr/local/share/certs/ca-root-nss.crt
    CApath: none


update
```

The error message is too cryptic. What went really wrong?
If there is a problem with the certificates, why isn't this displayed in the admin panel when doing generic checks?

Exception from the logs
```
[04-Feb-2017 12:06:36 Europe/Zurich] PHP Fatal error:  Uncaught Exception: Could not do request to updater server: error setting certificate verify locations:
  CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none in /updater/index.php:514
Stack trace:
#0 /updater/index.php(224): Updater->getUpdateServerResponse()
#1 /updater/index.php(1443): Updater->checkForUpdate()
#2 {main}
  thrown in /updater/index.php on line 514
```

**Comment by oparoz** [comment]
Never mind tge cert wasn't readable by the user...

**Comment by oparoz** [comment]
We need 3 things:

1. Display an error message in the admin panel if the CAfile is not readable by the PHP user
1. Display an error message, inviting the user to check the logs (if we don't want to show the message in the frontend)
1. Make the error message less cryptic if possible

**Comment by MorrisJobke** [comment]
Ummm ... Looks like the certificate chain isn't valid for your system. Or am I wrong @LukasReschke

**Comment by oparoz** [comment]
It was actually a permission problem, the user didn't have the rights to read it, but the problem is more that admins don't get any feedback in the GUI.

**Comment by MorrisJobke** [comment]
> It was actually a permission problem, the user didn't have the rights to read it, but the problem is more that admins don't get any feedback in the GUI.

Could you write how to reproduce this?

**Comment by oparoz** [comment]
Sure.

1. Configure a CAfile for Nextcloud/PHP
1. Make the file owned by root or another user
1. Launch the updater

**Comment by Varbin** [comment]
So, how to find out what the real problem is with this "precise" error message? My updater completely broke because of a similar error. As the error message is still the same for all the errors, I have no clue how to fix it (now on NC 13 b3).
